<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>S3903;NU1701</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EFCore.BulkExtensions" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.5" />
    <PackageReference Include="N.EntityFrameworkCore.Extensions" Version="10.0.5" />
    <PackageReference Include="SonarAnalyzer.CSharp" Version="10.22.0.136894">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PersistenceDb.Repository\PersistenceDb.Repository.csproj" />
  </ItemGroup>
</Project>
